### ISSUE TITLE
Only magnet files? How to make sonarrto provide them ?

### ISSUE THREAD

**Issue by dabonzo** [JackDallas/Premiumizearr#51]
I'm using premiumizearr in a docker container as part of a bigger docker stack including the other arr's (sonarr, readarr, radarr, jackett and others)
Here's the service portion of the stacks premiumizearr's service:
```
premiumizearr:
    container_name: premiumizearr
    image: ghcr.io/jackdallas/premiumizearr:latest
    restart: unless-stopped
    networks:
      - the_arrs_network
    ports:
      - 8182:8182
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MOUNT_POINT}/configs/premiumizearr:/data
      - ${MOUNT_POINT}/data/premiumize/in:/blackhole
      - ${MOUNT_POINT}/data/premiumize/out:/downloads
```
For example sonarr:
I can select an episode and it saves the torrent file in the correct folder, but in the description it says only magnet files are supported. So nothing happens. Will there be a .torrent support or how do I save magnet files from sonarr? I didn't find such an option.
